# Generated by Django 3.2.7 on 2021-09-06 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentindexpage',
            old_name='intro',
            new_name='body',
        ),
    ]
